#!/usr/bin/bash

# Send prefix
set-option -g prefix C-n
unbind-key C-n
bind-key C-n send-prefix

# Use Alt-arrow keys to switch panes
bind -n M-H select-pane -L
bind -n M-L select-pane -R
bind -n M-K select-pane -U
bind -n M-J select-pane -D

# Shift arrow to switch windows
#bind -n S-Left previous-window
#bind -n S-Right next-window
bind -n M-h previous-window
bind -n M-l next-window

# Mouse mode
setw -g mouse on

# Set easier window split keys/Open splits in the same dir
bind-key v split-window -h -c '#{pane_current_path}'
bind-key h split-window -v -c '#{pane_current_path}'

# Open new window in the same dir
bind c new-window -c"#{pane_current_path}"

# Easy config reload
bind-key r source-file ~/.tmux.conf \; display-message "tmux config reloaded!"

# Trying to tmux to render 256 colors
set -g default-terminal "screen-256color"

# Styles
set-option -g status-style bg="#292c3b"

# Left
#set-option -g status-left "#[fg=color235,bg="#a1cd5e"]Session:#{session_name} "
set-option -g status-left "#[fg=color235,bg="#82aaff"] Session:#{session_name} #[bg="#292c3b",fg="#82aaff"] "
set-option -g status-left-length 20

    
set-option -g status-right "#(date +'%a %b %d %I:%M%p ')" 
set-option -g status-right-length 54

# Window/Middle
set-option -g window-status-format "#[fg="#f5aea2"]#{window_index}:#{window_name} #[fg="#11121b"]" 
set-option -g window-status-current-format "#[fg="#29ea18"]#{window_index}:#{window_name} #[fg="#11121b"]"

# set windows and panes 1 indexed and not zero indexed
set -g base-index 1
setw -g pane-base-index 1
