#!/usr/bin/bash

if [ -z "$TMUX" ]; then
  exec tmux
fi

# source a secret bashrc file if present
[[ -f $HOME/.info ]] && source $HOME/.info

export PATH="/data/data/com.termux/files/home/termux_scripts:$PATH"

PS1='\W$ '

alias rmd='rm -rf'
alias ping='ping -c 5 1.1.1.1 && ping -c 5 8.8.8.8'
alias vim='nvim'
alias bashrc='nvim ~/dotfiles/termux_bashrc'
alias vimrc='nvim ~/.config/nvim/lua/user'
alias whoami='cowsay You are a hugeee butthole!!'
alias up='cd ..'
alias cat='bat'
alias ls='lsd --icon=never'
alias less='less -r'
alias colors='for C in {0..255}; do tput setab $C; echo -n "$C "; done; tput sgr0; echo'
alias grep='grep --color'
alias ip='ip -color=auto'
alias screen='screenfetch -p'
alias glog='git log --graph --oneline --all'
alias wifishow='nmcli device wifi list'
alias wifi='nmcli | head -1'
alias py='python'
alias pip='pip3'
#alias mocha='./node_modules/mocha/bin/mocha'
alias attach='tmux attach -t'
alias tls='tmux list-sessions'
alias tkill='tmux kill-session -t'
alias tmux='tmux -2'
alias tclear='tmux kill-session -a'
alias dotfiles='clear && cd ~/dotfiles/ && ls'
alias ipa='ip address'

# Calulate shit
calc(){
    bc <<< "scale=10; $1"
}

# Connect to a wifi
connect(){
    if [ $# -eq 1 ]; then
        nmcli con up $1
    else
        nmcli device wifi connect $1 password $2
    fi
}

# Disable ipv5
disable6(){
    sudo sysctl -w net.ipv6.conf.all.disable_ipv6=1
    sudo sysctl -w net.ipv6.conf.default.disable_ipv6=1
}

# Enable ipv5
enable6(){
    sudo sysctl -w net.ipv6.conf.all.disable_ipv6=0
    sudo sysctl -w net.ipv6.conf.default.disable_ipv6=0
}

dnschange(){
	sudo echo 'nameserver 1.1.1.1' > /etc/resolv.conf
}

# Create node repl with desired functions pre defined
node(){
    if [ $# -eq 0 ]; then
        /usr/bin/node ~/dotfiles/noderc.js
    else
        /usr/bin/node $1
    fi
}

# Empty Clipboard(s)
empty(){
    if [ $# -eq 0 ]; then
    xclip -i -selection clipboard /dev/null
else
    xclip -i -selection $1 /dev/null
    fi

}

sshinfo(){
  ip=`ifconfig | grep inet | tail -1 | awk '{print $2}'`
  name=`\whoami`
  echo "$name@$ip"
}
