" Normal Mode
" Go to the end of the beginning of the line
nnoremap <C-e> $
nnoremap <C-a> 0

" Semicolon for colon
nnoremap ; :

" Copy till the end of line
nnoremap Y y$

" Copying command TBD
" nnoremap <C-v> "+p
" nnoremap cv "+p

" Show registry of buffer
nnoremap <C-q> :reg<CR>

" Clear serach
nnoremap nh :nohl<CR>

" Insert Mode 
inoremap qq <Esc>
inoremap <C-e> <Esc>A
inoremap <C-a> <Esc>0i
inoremap <C-h> <Left>
inoremap <C-l> <Right>
inoremap <C-k> <Up>
inoremap <C-j> <Down>
inoremap <C-u> <ESC>ui
inoremap <C-d> <Esc>ddi
inoremap ;; <Esc>:
inoremap <C-b> <Esc>GA
inoremap zz <Esc>zz
inoremap <C-q> <Esc> :reg<CR>
inoremap <C-0> <Esc>0i

" Visual Mode
vnoremap qq  <Esc>
vnoremap <C-c> "+y


" Command Mode
cnoremap qq q! 

" Terminal Mode
tnoremap qq <C-\><C-n>
