require("dave.options")
require("dave.mappings")
require("dave.splits")
require("dave.plugins")
require("dave.statusline")
require("dave.treesitter")
require("dave.vimscripts")
require("dave.autopairs")
require("dave.comments")
require("dave.gitsigns")
require("dave.nerdtree")
require("dave.cmp")
require("dave.mason")
require("dave.copilot")

